export enum ActionTypes {
  GET_CONFERENCES_START = "GET_CONFERENCES_START",
  GET_CONFERENCES_SUCCESS = "GET_CONFERENCES_SUCCESS",
  GET_CONFERENCES_FAILURE = "GET_CONFERENCES_FAILURE",
  SET_CURRENT_CONFERENCE_ID = "SET_CURRENT_CONFERENCE_ID",
}
