export enum ActionTypes {
  GET_PROPOSALS_START = "GET_PROPOSALS_START",
  GET_PROPOSALS_SUCCESS = "GET_PROPOSALS_SUCCESS",
  GET_PROPOSALS_FAILURE = "GET_PROPOSALS_FAILURE",
  ADD_PROPOSAL_START = "ADD_PROPOSAL_START",
  ADD_PROPOSAL_SUCCESS = "ADD_PROPOSAL_SUCCESS",
  ADD_PROPOSAL_FAILURE = "ADD_PROPOSAL_FAILURE",
  GET_REVIEWS_FOR_PROPOSAL_START = "GET_REVIEWS_FOR_PROPOSAL_START",
  GET_REVIEWS_FOR_PROPOSAL_SUCCESS = "GET_REVIEWS_FOR_PROPOSAL_SUCCESS",
  GET_REVIEWS_FOR_PROPOSAL_FAILURE = "GET_REVIEWS_FOR_PROPOSAL_FAILURE",
  SET_CURRENT_PROPOSAL = "SET_CURRENT_PROPOSAL",
}
